### ISSUE TITLE
Retty Roadmap

### ISSUE THREAD

**Issue by rainliu** [retty-io/retty#1]
Here is the roadmap of Retty project:

# v0.1.1 (09/26/2022)
- [x] TCP server bootstrap 
- [x] Handler and Pipeline 

# v0.1.2 (09/27/2022)
- [x] TCP client bootstrap 

# v0.2.0 (10/01/2022)
- [x] UDP server/client bootstrap 
- [x] Async Transport Trait to unify TCP and UDP sockets

# v0.3.0 (10/02/2022)
- [x] add cancellation handling for bootstrap_tcp/udp_server
- [x] add abstraction for async runtime in order to support both tokio and async-std

# v0.4.0 (01/14/2023)
- [x] https://github.com/retty-io/retty/issues/2

# v0.5.0 (01/16/2023)
- [x] refactor InboundHandlerGeneric/OutboundHandlerGeneric to InboundHandler/OutboundHandler
- [x] refactor InboundHandler/OutboundHandler to InboundHandlerInternal/OutboundHandlerInternal
- [x] remove internal Message type

# v0.6.0 (01/20/2023)
- [x] make Inbound/OutboundHandler/HandlerContext as Trait with Associated Types

# v0.6.1 (01/21/2023)
- [x] make Documentation complete

# v0.7.0 (01/22/2023)
- [x] refactoring OutboundHandlerContext<Win,Wout> to OutboundHandlerContext and InboundHandlerContext<Rin,Rout> to InboundHandlerContext
- [x] update lib.rs documentation with echo server example

# TBD 
- [ ] make pipeline as Generic
- [ ] add more unit tests
- [ ] add more examples
